Create header and headline
Xecyc/My-Portfolio-Project-outdated- pull request #1
Opened 2023-03-24 18:49 UTC by Xecyc

This is the first pull request for my portfolio project. In this pull request, I have:

- Created the toolbar that includes the log and the ham menu
- Created the headline of the project

2023-03-24 19:46 UTC, vickymarz requested changes
Hi @Xecyc, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- Good UI design ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 19:46 UTC, vickymarz commented on index.html
> +      <h1>Hey there. I'm Edu<span>I'm a software developer</span></h1>
- [ ] Good job so far.  Kindly ensure that the subtitle (e.g _I'm a software developer_) uses a header tag hx (examples`<h2>`, etc...) to improve the accessibility of your website so that search engines and screen readers can understand that the text is a subtitle of the main heading 👍🏽

2023-03-24 19:46 UTC, vickymarz commented on index.html
> +        <a href="#"><img tabindex="0" src="/img/Unionham.svg" alt="hamburger-menu-icon" class="ham-img"></a>
- [ ] All your images in your project seem not to be displayed at the moment. so I think you should add a dot (.) to the relative path of the images so that the images can display 👍🏽 
 e.g 
`src="./img/Unionham.svg"`

2023-03-24 22:15 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Xecyc 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow

## Required Changes ♻️
_Please kindly check the comments under the review._
### ♦♦Your commit messages are not descriptive ♦♦

![image](https://user-images.githubusercontent.com/78251927/227652977-7c7ee950-e6d0-485f-8631-fde3278ec525.png)

Please let's always use descriptive commit messages - each commit should be small enough to describe it in one sentence. The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8).

As it is not easy to change commit history, please kindly correct this behavior in the future 👍

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 22:15 UTC, abdulhamiid commented on index.html
> +        <a href="#"><img tabindex="0" src="/img/Unionham.svg" alt="hamburger-menu-icon" class="ham-img"></a>
As requested by the previous reviewer, please kindly fix the hamburger button which is currently not displaying
There is a typo with your code `src="/img/Unionham.svg"` 

Your design
![image](https://user-images.githubusercontent.com/78251927/227652130-d2cccadc-4bce-4971-9996-98d2fe6410f5.png)

Figma
![image](https://user-images.githubusercontent.com/78251927/227652037-d0741080-84a1-4152-9d24-37af020c90b5.png)

To fix this, let's change the relative path to `src="./img/Unionham.svg"`. i.e there is a dot before `/`

2023-03-25 00:11 UTC, tresorsawasawa approved these changes

2023-03-25 00:12 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Xecyc 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 19:25 UTC, merged