Create projects and about-me sections
Xecyc/My-Portfolio-Project-outdated- pull request #2
Opened 2023-03-30 17:01 UTC by Xecyc

In this pull request, I will create the projects section, and the about-me section. I did use grid but only in small sections of the design, I didn't find many optimal ways to utilize it in a mobile design, I hope it isn't a big issue.

What I've done:

- Created projects section
- Created about-me section
- Skills/abilities section
- Made several improvements to the html and css code from the previews pull request.

2023-03-30 17:55 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Xecyc 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 17:55 UTC, abdulhamiid commented on index.html
> +      <div class="works-section">
According to the project requirements, It is important that we use `CSS Grid` in the main container i.e `<div class="works-section">` that contains all of the cards. 

Please let's implement that in your styling. 🤗 👍

2023-03-30 17:55 UTC, abdulhamiid commented on index.html
> +          </div>
Please kindly remove the outer `<div>` tag and use only a link `a` or `button` tag for the `See Project` button. That way it will be semantically correct 👍. 

That way, when the button is clicked, the user is clicking on the `<a>` tag and not the `<div>`.

Also, kindly implement the button styling: `Active`, `Hover`, and `Pressed`. according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md)

See design
![image](https://user-images.githubusercontent.com/78251927/228916678-0af88ab4-8b75-4523-8bd5-43e22b46651d.png)

2023-03-30 17:55 UTC, abdulhamiid commented on index.html
> +              <li class="list-area area-3">Ruby</li>
Please let's update the list of project technologies to follow the correct convention in writing the technologies' names. 👍 i.e `HTML` not `html` 😉 to match the template on Figma.

Figma
![image](https://user-images.githubusercontent.com/78251927/228919038-e67a0d72-ec84-4a29-8367-1e59cea2167b.png)

2023-03-30 17:55 UTC, abdulhamiid commented on index.html
> +    <section class="about_me">
Figma
![image](https://user-images.githubusercontent.com/78251927/228920066-ab69ee69-bee4-46ac-a862-24f46fa9ed26.png)

Your design
![image](https://user-images.githubusercontent.com/78251927/228919529-02bd5562-1a97-412f-b384-340e64f9d1fb.png)

Kindly add the section margins (top, bottom, left, right) defined in the design. 💪

2023-03-30 17:55 UTC, abdulhamiid commented on index.html
> +        <hr>
As requested earlier in the review, please let's also remove the outer `<div>` tag and use only a link `a` or `button` tag for the `See Project` button. 👍

2023-03-31 00:41 UTC, Alfredbis29 approved these changes
# STATUS: APPROVED   
 ## Hi @Xecyc 
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Well structured files :white_check_mark:
 * Good Job :+1: :smile: 
 
 Now you can merge this branch and move on 1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions

- [x] check under the  review :wink: 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 00:41 UTC, Alfredbis29 commented on index.html
> +      <div class="headline-container">
- [ OPTIONAL] You did a great job on this project but it could be better if your design match the Figma design for it to look more attractive so that recruiters can reach you, kindly fix this :wink:  :point_down: 
 Compare your Design to the Figma one there are some differences, your social media should be in the same line with the icon on the right as we can see on Figma design :wink: 

Your Design 
![Screenshot from 2023-03-31 02-29-57](https://user-images.githubusercontent.com/88894525/228993684-1d94beba-a85f-4ee8-a588-9eab5aa443a9.png)

Figma Design 
![Screenshot from 2023-03-31 02-27-22](https://user-images.githubusercontent.com/88894525/228993717-18d94793-9753-4ffa-940a-2738fd109690.png)

2023-03-31 01:17 UTC, merged